"""On-demand exports preserve outlines; cross-outline conversion is not implicit.

Cache identity is physical face + output container + exporter version. Source
instances share generated bytes, while original downloads preserve provenance.
Only queued exports compress. GET/status endpoints never perform conversion.
"""
import hashlib
import json
import time
from pathlib import Path
from flask import jsonify, request, abort, send_file
from fontTools.ttLib import TTFont
from font_analysis import usable_cmap
from archive_io import publish, archive_lock
import import_queue
import original_checks
from archive_pipeline import heavy

FORMATS=('ttf','otf','woff','woff2')
VERSION='1'

def key(face_id,format):
    return face_id.split('~')[0]+'|'+format+'|'+VERSION

def cached(data,face_id,format):
    return data/'exports'/(key(face_id,format).replace('|','-')+'.'+format)

def native(path,index):
    # sfntVersion identifies the preserved outline container even inside WOFF.
    with TTFont(path,fontNumber=index,lazy=True) as font:
        return 'otf' if font.sfntVersion=='OTTO' else 'ttf'

def register(app,db,data,resolve_face,client,source_data):
    (data/'exports').mkdir(exist_ok=True)
    def context(public_id):
        with db() as con:
            face=resolve_face(con,public_id)
            row=con.execute('SELECT files.* FROM files JOIN faces ON files.hash=faces.hash WHERE faces.id=?',(face['id'].split('~')[0],)).fetchone()
        return face,dict(row)
    def options(public_id):
        face,row=context(public_id);physical=face['id'].split('~')[0];index=int(physical.rsplit('-',1)[1])
        with db() as con: admitted=original_checks.allowed(con,row['hash'],face['source'])
        try: base=native(row['path'],index) if admitted else None;reason='' if admitted else 'Нужен допуск OTS: см. Карантин и ошибки'
        except Exception: base=None;reason='Не удалось прочитать структуру оригинала'
        with db() as con:
            jobs={j['identity']:dict(j) for j in con.execute("SELECT * FROM work_queue WHERE kind='convert' AND identity LIKE ?",(physical+'|%',))}
        with db() as con:
            preview_job=con.execute("SELECT * FROM work_queue WHERE kind='preview' AND identity=?",(physical,)).fetchone()
        rows=[]
        for format in FORMATS:
            path=cached(data,physical,format);job=dict(preview_job) if format=='woff2' and preview_job else jobs.get(key(physical,format));same=Path(row['name']).suffix.lower()=='.'+format and index==0
            # TTC originals always download as collections, never masquerade as one face.
            preview=data/'previews'/(physical+'.woff2')
            preview_ready=format=='woff2' and face.get('preview_available') and preview.is_file()
            if preview_ready: path=preview
            ready=same or preview_ready or (path.is_file() and bool(job) and job['status']=='done')
            supported=base is not None and format in (base,'woff','woff2')
            rows.append(dict(format=format.upper(),id=format,status='ready' if ready else job['status'] if job else 'available' if supported else 'unavailable',method='Оригинал' if same else 'Конвертация',size=Path(row['path']).stat().st_size if same else path.stat().st_size if ready else None,error=job['error'] if job else reason if not base else 'Потребуется изменение контуров' if not supported else '',url='/download/'+public_id if same else '/download-export/'+public_id+'/'+format if ready else None,supported=supported))
        return dict(style=face['style'],rows=rows,original=dict(url='/download/'+public_id,format=face['format'],size=Path(row['path']).stat().st_size,name=row['name']))
    @app.get('/api/fonts/<face_id>/exports')
    def export_status(face_id): return jsonify(options(face_id))
    @app.post('/api/fonts/<face_id>/exports/<format>')
    def request_export(face_id,format):
        if format not in FORMATS: abort(400)
        row=next(r for r in options(face_id)['rows'] if r['id']==format)
        if row['url']: return jsonify(row),200
        if not row['supported']: return jsonify(error=row['error']),422
        face,original=context(face_id)
        if format=='woff2':
            # Share the complete browser artifact, compression and OTS validation.
            with db() as con: import_queue.enqueue_preview(con,face['id'].split('~')[0],original['path'],original['name'],face['source'])
            return jsonify(status=row['status'] if row['status'] in ('queued','running','error') else 'queued',queue_url='/imports'),202
        with db() as con:
            con.execute("INSERT INTO work_queue(kind,identity,input_path,filename,source,created) VALUES('convert',?,?,?,?,?) ON CONFLICT(kind,identity) DO NOTHING",(key(face_id,format),original['path'],face['family']+' '+face['style']+'.'+format,face['source'],time.time()))
            con.execute("UPDATE work_queue SET status='queued',phase='waiting',error='',started=NULL,finished=NULL WHERE kind='convert' AND identity=? AND status='done'",(key(face_id,format),))
        return jsonify(status=row['status'] if row['status'] in ('queued','running','error') else 'queued',queue_url='/imports'),202
    @app.get('/download-export/<face_id>/<format>')
    def download_export(face_id,format):
        if format not in FORMATS: abort(400)
        face,_=context(face_id);path=cached(data,face_id,format)
        with db() as con: job=con.execute("SELECT status FROM work_queue WHERE kind='convert' AND identity=?",(key(face_id,format),)).fetchone()
        preview=data/'previews'/(face['id'].split('~')[0]+'.woff2')
        if format=='woff2' and face.get('preview_available') and preview.is_file(): path=preview
        elif not job or job['status']!='done' or not path.is_file(): abort(404)
        name=''.join(c for c in face['family']+'-'+face['style'] if c not in '<>:"/\\|?*' and ord(c)>=32).strip('. ') or 'font'
        return send_file(path,as_attachment=True,download_name=name+'.'+format)

def process(db,data):
    with db() as con: job=import_queue.claim(con,'convert')
    if not job: return False
    with db() as con:
        if not original_checks.guard(con,job,job['identity'][:64]):return True
    with heavy(data,Path(job['input_path'])):
        return process_job(db,data,job)


def process_job(db,data,job):
    physical,format,version=job['identity'].split('|');target=cached(data,physical,format);partial=target.with_suffix('.export.part')
    try:
        with db() as con: row=con.execute('SELECT faces.metadata,files.hash FROM faces JOIN files ON files.hash=faces.hash WHERE faces.id=?',(physical,)).fetchone()
        if not row: raise ValueError('Начертание удалено из каталога')
        metadata=json.loads(row['metadata']);original=Path(job['input_path'])
        with original.open('rb') as stream:
            if hashlib.file_digest(stream,'sha256').hexdigest()!=row['hash']: raise ValueError('Контрольная сумма оригинала не совпала')
        expected=set(metadata['chars'])
        def valid(path):
            try:
                with TTFont(path) as font: return set(usable_cmap(font)[0])==expected and font.flavor==({'woff':'woff','woff2':'woff2'}.get(format)) and ('otf' if font.sfntVersion=='OTTO' else 'ttf')==native(original,int(physical.rsplit('-',1)[1]))
            except Exception: return False
        # A valid published file may survive a crash before SQLite completion.
        if not target.is_file() or not valid(target):
            with db() as con: import_queue.progress(con,job['id'],'conversion')
            with TTFont(original,fontNumber=int(physical.rsplit('-',1)[1])) as font:
                usable_cmap(font)
                base='otf' if font.sfntVersion=='OTTO' else 'ttf'
                if format not in (base,'woff','woff2'): raise ValueError('Изменение контуров не поддерживается')
                font.flavor=format if format in ('woff','woff2') else None
                font.save(partial)
            with db() as con: import_queue.progress(con,job['id'],'verification')
            if not valid(partial): raise ValueError('Проверка экспортированного файла не пройдена')
            with archive_lock(data/'import.lock'): publish(partial,target)
        with db() as con: import_queue.finish(con,job['id'],result=physical+'~'+job['source'])
    except Exception as exc:
        partial.unlink(missing_ok=True)
        with db() as con: import_queue.finish(con,job['id'],'error',str(exc)[:1000])
    return True
